@startuml

title: クッキーの送受信の流れ
hide footbox

group ファーストパーティクッキーの送受信
  ブラウザ -> "同一ドメインのサーバ\n（webページを返すサーバ）" : ・見たいwebページの情報をリクエストする\n・保持しているクッキーを送信する
  "同一ドメインのサーバ\n（webページを返すサーバ）" -> ブラウザ: webページの情報（クッキー含む）を返す
end

|||

group サードパーティクッキーの送受信
  ブラウザ -> "異なるドメインのサーバ\n（広告配信サーバ）": ・webページ内の広告情報をリクエストする\n・保持しているクッキーを送信する
  "異なるドメインのサーバ\n（広告配信サーバ）" -> ブラウザ: 広告情報（クッキー含む）を返す

  note over ブラウザ, "異なるドメインのサーバ\n（広告配信サーバ）": AdSenseの場合、以下の場合にブラウザにCookieが送信される可能性がある\n* 広告が表示された（最も一般的なケース）\n* 広告がクリックされた\n* 表示されたwebページ内に広告タグが含まれている
end

@enduml