@startuml

title "ドキュメント管理システム"

skinparam Linetype ortho

/' 
  イベント系テーブル：E
  リソース系テーブル：R
'/

!define EVENT_MARK_COLOR AAFFAA
!define RESOURCE_MARK_COLOR FFAA00

package "ドキュメント" as documentpkg {
  entity "ドキュメント" as document <<R, RESOURCE_MARK_COLOR>> {
    + ドキュメントID <<PK>>
    ---
    ドキュメント名
    ドキュメント配置場所
    ユーザID <<FK>>
    ディレクトリID <<FK>>
    更新日時
  }

  note right of document::ドキュメント配置場所
    ドキュメント自体は、別のストレージ
    に保存するため（DBには保存しない）
    その配置ディレクトリやURLなどを
    このカラムの値として保持する
  end note

  note right
    最新のドキュメントを保持する
  end note

  entity "ドキュメント履歴" as document_history <<E, EVENT_MARK_COLOR>> {
    + ドキュメント履歴ID <<PK>>
    ---
    ドキュメントID <<FK>>
    ドキュメント名
    ドキュメント配置場所
    ユーザID <<FK>>
    ディレクトリID <<FK>>
    更新日時
  }
  
  note left
    過去のドキュメントを保持する
    ドキュメントが更新または削除された場合に、
    TRIGGERによってこのテーブルにレコードがINSERTされる
    ---
    削除された場合は、削除された最後のドキュメントがINSERTされる
    アプリケーション側では、
    ドキュメントテーブルにそのドキュメントIDのレコードが存在しないことで
    削除されたと判断することができる
  end note
}

package "ディレクトリ" as directorypkg {
  entity "ディレクトリ" as directory <<R, RESOURCE_MARK_COLOR>> {
    + ディレクトリID <<PK>>
    ---
    ディレクトリ名
    ディレクトリ作成日
    アドミン管理ID <<FK>>
  }

  entity "アドミン管理" as admin_management <<R, RESOURCE_MARK_COLOR>> {
    + アドミン管理ID <<PK>>
    ---
    ディレクトリID <<FK>>
    ユーザID <<FK>>
  }

  note left of admin_management::ユーザID
    1つのディレクトリに対して、
    アドミンユーザは複数名存在し得る
    アドミンユーザはディレクトリにおける全ての操作が可能なため
    ディレクトリ所属テーブルにはアドミンユーザー用のレコードは存在しない
  end note

  entity "ディレクトリ関係" as directory_relation <<R, RESOURCE_MARK_COLOR>> {
    + ディレクトリ関係ID <<PK>>
    ---
    親ディレクトリID <<FK>>
    子ディレクトリID <<FK>>
  }
}

package "ユーザ" as userpkg {
  entity "ユーザ" as user <<R, RESOURCE_MARK_COLOR>> {
    + ユーザID <<PK>>
    ---
    ユーザ名
  }

  entity "ディレクトリ所属" as user_belongings <<R, RESOURCE_MARK_COLOR>> {
    + 所属ディレクトリID <<PK>>
    ---
    ユーザID <<FK>>
    ディレクトリID <<FK>>
    操作権限ID <<FK>>
  }

  entity "操作権限" as priviledge <<R, RESOURCE_MARK_COLOR>> {
    + 操作権限ID <<PK>>
    ---
    権限名
  }

  note right of priviledge::権限名
    以下の権限を想定
    * 追加
    * 編集
    * 削除
  end note
}

document }o--|| directory
document }o--|| user
directory ||-l-|{ directory_relation
directory ||-l-|{ directory_relation
document ||-l-o{ document_history
user ||--o{ user_belongings
user_belongings }o--|| priviledge
directory ||--|{ admin_management
user ||--o{ admin_management
directory ||--o{ user_belongings

@enduml