name: toc-generate

# developブランチにプッシュされた場合のみ起動
on: 
  push:
    branches:
      - "feature/*"

# with以下でtoc-generatorの設定を指定
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: toc-generator
        uses: technote-space/toc-generator@v3
        with:
          FOLDING: true
          TOC_TITLE: "**目次**"
          COMMIT_MESSAGE: "docs: toc-generatorによる目次自動作成\n#7"
          TARGET_PATHS: "**/*.md"
  
  slack-notify:
    if: always()
    needs: [generateTOC]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: 'Github Actions Workflow'
          channel: '#pair-1c-notification'
          icon_url: 'https://user-images.githubusercontent.com/47489629/104346721-16e1d200-5543-11eb-869f-80ac22ee4501.png'
    
