name: toc-generate

# developブランチにプッシュされた場合のみ起動
on: 
  push:
    branches:
      - develop

# with以下でtoc-generatorの設定を指定
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          TOC_TITLE: "**目次**"
          FOLDING: true
          COMMIT_MESSAGE: "#7 Add or Update: 目次作成"
          TARGET_PATHS: "*.md,web_basic/*.md,web_basic/http_header/*.md"
