name: toc-generate

# developブランチにプッシュされた場合のみ起動
on: 
  push:
    branches:
      - develop

# with以下でtoc-generatorの設定を指定
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v3
        with:
          TOC_TITLE: "**Details**"
          FOLDING: true
          COMMIT_MESSAGE: "docs: toc-generatorによる目次自動作成\n#7"
          TARGET_PATHS: "**/*.md"
